### PR TITLE
Using C# 7 pattern matching features

### PR DESCRIPTION
**Pull request by bartdesmet**
Some trivial changes to use more C# 7.0 features.

### CODE REVIEW

**Comment by bartdesmet** [comment]
@onovotny @shiftkey - There seem to be build issues:

```
[00:01:59]      2>SourceLinkCreate:
[00:01:59]          unable to find repository origin with: dotnet sourcelink-git origin
[00:01:59]      2>Done Building Project "C:\projects\rx-net-la3iv\Rx.NET\Source\src\System.Reactive\System.Reactive.csproj" (default targets) -- FAILED.
```

Any thoughts what's off?

**Comment by shiftkey** [comment]
@bartdesmet looks like something with the sourcelink setup

**Comment by onovotny** [comment]
I just bumped sourcelink to version 2.1, lets see if that helps. Otherwise, we can loop in @ctaggart to help.

**Comment by onovotny** [comment]
I've worked around this in dev by disabling sourcelink until @ctaggart can investigate further. Builds are green now.

**Pull request merged**
