### PR TITLE
[WIP] Asynchronous Rx implementation

### PR DESCRIPTION
**Pull request by bartdesmet**
This pull request contains an initial implementation of "Async Rx" with the following essential interfaces:

* `IAsyncObservable<T>`, the dual to `IAsyncEnumerable<T>` and the async variant of `IObservable<T>`
* `IAsyncObserver<T>`, the dual to `IAsyncEnumerator<T>` and the async variant of `IObserver<T>`
* `IAsyncSubject<T>`, the async variant of `ISubject<T>`
* `IAsyncDisposable`, the async variant of `IDisposable`
* `IAsyncScheduler`, the async variant of `IScheduler`

Note that this PR is work in progress. While it has most operators implemented, there's some outstanding design work and a ton of testing to be done. The main goals of this initial PR are:

* research the duality with the latest "async streams" proposal in C# 8.0;
* get a feel for the APIs and the overload bloat for async variants;
* noodle around with different implementation techniques, e.g. observer operators;
* give the resulting prototype a spin in practice.

Interface variants would be possible with regards to supporting `CancellationToken` parameters, but it brings similar pains as the ones observed (pun intended) by the LDM for the C# 8.0 design of async streams. As such, this initial implementation uses a "cancellation agnostic" approach, though further study is warranted.

In the context of Rx, the use of `CancellationToken` in various places clearly shows the pain these induce on top of the algebra of sequences, e.g. any cancellation of an `On*Async` call leaves observers in indeterminate states, so termination of the subscription is warranted, which indicates that the `IAsyncDisposable` handle to the subscription and any `CancellationToken`s for event flow aren't orthogonal. Similar concerns occur when attempt to cancel the creation of a subscription.

While more fine-grained control over cancellation can be useful for service abstractions of Rx (as done in the "Reactor" project in Bing) that cross I/O boundaries, such distributed abstractions could be regarded as being layered on top (i.e. we don't need a "one size fits all" interface necessarily). In fact, other orthogonal requirements are imposed in the distributed variants, such as the ability to pass in explicit identifiers for resources. More on that another time.

### CODE REVIEW

**Comment by BigBabay** [comment]
Hi, great job, want to use it in our project. Can you answer, how long time acceptance of PR can take?

**Comment by pekkah** [comment]
Any news on this?

**Comment by bartdesmet** [comment]
Merging this initial prototype as-is, with future development planned after `IAsyncEnumerable<T>` is set in stone and the interface duality can be re-evaluated.

**Comment by petroemil** [comment]
@bartdesmet would you be able to provide any news on the development of these set of features and/or potentially the progress of opening up Reactor to the public?

**Comment by minimal-dev** [comment]
Any news about `Asynchronous Rx implementation` in 2019?

**Comment by pihai** [comment]
Any news about Asynchronous Rx implementation in 2020?

**Comment by casperOne** [comment]
2022 perhaps?

**Pull request merged**
