### PR TITLE
Extend RefCountDisposable to support throwing ObjectDisposedExceptions w...

### PR DESCRIPTION
**Pull request by danielcweber**
...hen GetDisposable is called after the RefCountDisposable has been disposed.

---
This change is [Reviewable](https://reviewable.io/reviews/reactive-extensions/rx.net/69)

### CODE REVIEW

**Comment by bartdesmet** [comment]
The change makes sense. I'm curious to know in which case you're using the new behavior? We'll consider this for the next release of Rx. Thanks!

**Comment by danielcweber** [comment]
Consider this class:

    class SomeClass : IDisposable
    {
        private RefCountDisposable _refCountDisposable;

        public SomeClass(IDisposabe resource)
        {
            this._refCountDisposable = new RefCountDisposable(resource);
        }

        public void DoSomethingWithResource()
        {
             using(this._refCountDisposable.GetDisposable())
             {
                  ....
             }
         }

         public void Dispose()
         {
             this._refCountDisposable.Dispose();
         }
    }

The requirements for this class are as follows:
1. `Dispose` and `DoSomethingWithResource` may be called at any time, on any thread.
2. The inner resource must not be disposed as long as `DoSomethingWithResource` executes.
3. After disposing the instance of `SomeClass`, the inner resource must be disposed when all calls to `DoSomethingWithResource` have completed.
4. Calling `DoSomethingWithResource` after calling `Dispose` throws an `ObjectDisposedException`.

The new behavior is needed for requirement 4. It can be emulated by checking `IsDisposed` within the `using` block, but having a disposed `RefCountDisposable`throw an `ObjectDisposedException` by itself is a much cleaner approach IMO.

**Comment by danielcweber** [comment]
I reviewed the above requirements and the commits from my pull request. As my pull request works right now, requirement 4 will not exactly be satisfied, but rather this:

4b. Calling `DoSomethingWithResource` after `Dispose` has been called throws an `ObjectDisposedException` if the `RefCountDisposable` has reached a zero count (i.e. all previous calls to `DoSomethingWithResource` have finished).

Which behaviour is more desireable may be the subject of further discussion.

**Comment by onovotny** [comment]
@mattpodwysocki @shiftkey @bartdesmet  thoughts for inclusion in the 3.0.1?

**Comment by mattpodwysocki** [comment]
@onovotny yep, let's do it

**Comment by onovotny** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Rx.NET/Source/System.Reactive.Core/Reactive/Disposables/RefCountDisposable.cs, line 1 \[r1\]](https://reviewable.io:443/reviews/reactive-extensions/rx.net/69#-KLTvWil-IgplMDOXJQv:-KLTvWimxsERIpUMm-xS:1185934686) ([raw file](https://github.com/reactive-extensions/rx.net/blob/0f9cd9726eb21c0dca2339f317762fcc612a989b/Rx.NET/Source/System.Reactive.Core/Reactive/Disposables/RefCountDisposable.cs#L1)):*
> ```Smalltalk
> // Copyright (c) Microsoft Open Technologies, Inc. All rights reserved. See License.txt in the project root for license information.
> ```

Please update copyright header to match other files in this repo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/reactive-extensions/rx.net/69)*

**Comment by onovotny** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/reactive-extensions/rx.net/69)*

**Comment by danielcweber** [comment]
Rebased onto latest master, should be good now.

**Pull request merged**
