### PR TITLE
Added SafeDisposable

### PR DESCRIPTION
**Pull request by Tuatan**
Some classes doesn't implement [IDisposable](https://msdn.microsoft.com/en-us/library/system.idisposable(v=vs.110).aspx) correctly and their Dispose implementation might throw.

### CODE REVIEW

**Comment by LeeCampbell** [comment]
This appears to be very similar to `AnonymousDisposable`, but public. Instead of having this type, users can use `Disposable.Create()` or alternatively `SingleAssignmentDisposable`.

No test coverage.

**Comment by Tuatan** [comment]
All disposable implementations could be created through `Disposable.Create()`, the point is to have a reusable fragment that allows to user code less. And this one cannot be replaced by  `SingleAssignmentDisposable `.

Test coverage could be added.

**Comment by LeeCampbell** [comment]
My point was that we could consider making `AnonDisposable` public (as it already does exactly what this new type does). Alternatives to

    var safeDisposable = new SafeDisposable(other);

could be 

    var safeDisposable = new SingleAssignmentDisposable { Disposable = other};

or 

    var safeDisposable = Disposable.Create(()=>other.Dispose());

With regards to using `Disposable.Create()` for all disposable implementations, that not true. Any of the mutable instances like `SingleAssignmentDisposable`, `SerialDisposable`, `MultiAssignmentDisposable`, `CompositeDisposable` could not be recreated with `Disposable.Create` without a serious amount of hackery.

I am not saying that we should not include `SafeDisposable`, but should first consider what other options there are before increasing the public surface area of the API.

**Comment by LeeCampbell** [comment]
And apologies, I missed the Try/Catch/Swallow part. I would not want this in the code base. Compensating behaviors for poorly designed APIs is a slippery slope in my opinion.

**Comment by Tuatan** [comment]
Yes, you are obviously right here, and according to the guidelines the implementation of Dispose should not throw, but even Task from TPL/FCL does throw on Dispose.

**Comment by RxDave** [comment]
It's true that `Task` throws on `Dispose` only in the case where disposing is an invalid operation, but it's not a great example of "acceptable" behavior given that, unlike most `IDisposable` implementations, the recommendation is to **not** dispose an instance of `Task` except in rare performance-related circumstances. (See http://blogs.msdn.com/b/pfxteam/archive/2012/03/25/10287435.aspx). The guideline that `Dispose` should never throw is still one that applies whenever it's recommended that calling `Dispose` is generally the right thing to do.

**Comment by Tuatan** [comment]
Dave, you are also correct here, usually task instance does not hold any disposable resources. I do realize that Try/Catch/Swallow is not particularly clean pattern to put it mildly, but an alternative option does not look really good as well:

`disposableInstance is Task ? Disposable.Empty : new SingleAssignmentDisposable{ Disposable =  disposableInstance }`

And in this cause you have to rely on application components that they did that as well.

**Comment by shiftkey** [comment]
Thanks for opening this @Tuatan but I'm :thumbsdown: on this change without understanding more about the context for the problem we're tackling here.

Now that we're close to getting 3.0 out the door, I think we can do something more elegant here.

**Pull request closed without merging**
