### PR TITLE
[WIP] enable source link

### PR DESCRIPTION
**Pull request by ctaggart**
Opening this PR, so that I can try debut the builds on AppVeyor. Source linking works locally. https://github.com/ctaggart/SourceLink/issues/167

### CODE REVIEW

**Comment by ctaggart** [comment]
@onovotny This looks ready. It was a bug in SourceLink. I released 2.0.3 with the bug fixed. Thanks for letting me troubleshoot here. I don't think the the latest build failure is related to enabling source link support.

**Comment by ctaggart** [comment]
The case ends up lower case for `source` folder in the pdb, so it is probably that way on disk. :-(
```
C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1 [dotnet-sourcelink ≡ +0 ~4 -0 !]> dotnet sourcelink print-documents "C:\Users\camer\Downloads\System.Reactive.4.0.0-PullReq00337.99\lib\net45\System.React
ive.dll"
2dce25745d3bf724e498ec9f0e2795a1c778e9c4 sha1 csharp C:\projects\rx-net-la3iv\Rx.NET\source\src\System.Reactive\Observable.Extensions.cs
059d8221fd2f1dda5261a633fe4eb2ab1891c76f sha1 csharp C:\projects\rx-net-la3iv\Rx.NET\source\src\System.Reactive\AnonymousObservable.cs
781f5827f60d7e96ca5d727e9ad4595ca14fb668 sha1 csharp C:\projects\rx-net-la3iv\Rx.NET\source\src\System.Reactive\AnonymousObserver.cs
714601d65172636014622dca235bdd81c4bce8e3 sha1 csharp C:\projects\rx-net-la3iv\Rx.NET\source\src\System.Reactive\AnonymousSafeObserver.cs
70ee78947925d1afcd97f18086385b935ec17530 sha1 csharp C:\projects\rx-net-la3iv\Rx.NET\source\src\System.Reactive\EventPattern.cs
eed64a5a0ccb089202f437e2667d08895b8aa099 sha1 csharp C:\projects\rx-net-la3iv\Rx.NET\source\src\System.Reactive\EventPatternSource.cs
b47d6714247901e027646e624f329b70f8cf8619 sha1 csharp C:\projects\rx-net-la3iv\Rx.NET\source\src\System.Reactive\EventPatternSourceBase.cs
8e9b7c091077e1a8b71be535788cc6b0b5bc6a81 sha1 csharp C:\projects\rx-net-la3iv\Rx.NET\source\src\System.Reactive\EventSource.cs
83b51a1a9e60825717d49493524b9e36bf8f633f sha1 csharp C:\projects\rx-net-la3iv\Rx.NET\source\src\System.Reactive\Internal\AnonymousEnumerable.cs
4c0d507077a4d023b53ea13f24bbe150bd7b644c sha1 csharp C:\projects\rx-net-la3iv\Rx.NET\source\src\System.Reactive\Internal\AsyncLockObserver.cs
```

**Comment by onovotny** [comment]
I'm pretty sure we attempted to change the case at one point which is why we're hitting this...that said, it's a scenario other ppl may hit for whatever reason too.

**Comment by ctaggart** [comment]
True. Do you know when it was changed? I'll troubleshoot this with my appveyor account where I can control the appveyor.yml.

**Comment by onovotny** [comment]
not sure...it was probably over a year ago :/

**Pull request closed without merging**
